### ISSUE TITLE
 scala.ScalaReflectionException: class Response is an inner class, use reflectClass on an InstanceMirror to obtain its ClassMirror

### ISSUE THREAD

**Issue by abhsrivastava** [gzoller/ScalaJack#140]
Parsing a json document is making ScalaJack throw the following error

```
[info]   scala.ScalaReflectionException: class Response is an inner class, use reflectClass on an InstanceMirror to obtain its ClassMirror
[info]   at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$abort(JavaMirrors.scala:115)
[info]   at scala.reflect.runtime.JavaMirrors$JavaMirror.ErrorInnerClass(JavaMirrors.scala:117)
[info]   at scala.reflect.runtime.JavaMirrors$JavaMirror.reflectClass(JavaMirrors.scala:183)
[info]   at scala.reflect.runtime.JavaMirrors$JavaMirror.reflectClass(JavaMirrors.scala:54)
[info]   at co.blocke.scalajack.typeadapter.CaseClassTypeAdapter$.typeAdapterOf(CaseClassTypeAdapter.scala:88)
[info]   at co.blocke.scalajack.TypeAdapterFactory$FromClassSymbol$class.typeAdapterOf(TypeAdapterFactory.scala:40)
[info]   at co.blocke.scalajack.typeadapter.CaseClassTypeAdapter$.typeAdapterOf(CaseClassTypeAdapter.scala:16)
[info]   at co.blocke.scalajack.TypeAdapterFactory$$anon$2.typeAdapterOf(TypeAdapterFactor
```

How can this be addressed?

**Comment by gzoller** [comment]
Can you include a clip of json that provokes this crash, plus the related class(es) youre trying to parse it into, plus any custom type adapters/modifiers if any.  I'll need enough to try and reproduce the problem, as there's really nothing I can tell from the exception other than it's not happy about something.
