### ISSUE TITLE
Suddenly ClassNotFoundException

### ISSUE THREAD

**Issue by pahlgrimm** [gzoller/ScalaJack#142]
Hi, now I'm having a new issue:
At first I had a simple SBT App and everything worked fine. Now I migrated the code into an actor in Play Framework and the JSON handling totally crashed. The code compiles fine but at Runtime I get the following error:
`java.lang.ClassNotFoundException: easybill.QueryResult$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at scala.reflect.runtime.ReflectionUtils$.staticSingletonInstance(ReflectionUtils.scala:64)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaModuleMirror.instance(JavaMirrors.scala:528)
	at co.blocke.scalajack.typeadapter.CaseClassTypeAdapter$.typeAdapterOf(CaseClassTypeAdapter.scala:92)
	at co.blocke.scalajack.TypeAdapterFactory$FromClassSymbol$class.typeAdapterOf(TypeAdapterFactory.scala:40)
	at co.blocke.scalajack.typeadapter.CaseClassTypeAdapter$.typeAdapterOf(CaseClassTypeAdapter.scala:16)`

The code looks like this:
` val result=ScalaJack().read[QueryResult[Customer]](response)`

Do you have any ideas?

Patrick

**Comment by pahlgrimm** [comment]
Nevermind I switched to circe (it has to run in the near future) and that works.

Thanks!
