### ISSUE TITLE
Denial of service when parsing JSON object with keys that have the same hash code

### ISSUE THREAD

**Issue by plokhotnyuk** [gzoller/ScalaJack#185]
_Sub-quadratic_ decreasing of throughput when number of JSON object fields (with keys that have the same hash code) is increasing

On contemporary CPUs parsing of such JSON object (with a sequence of 100000 fields like below that is ~1.6Mb) can took ~500 seconds:

```
{
"!!sjyehe":null,
"!!sjyeiF":null,
"!!sjyej'":null,
"!!sjyfIe":null,
"!!sjyfJF":null,
...
}
``` 

Below are results of the benchmark where `size` is a number of such fields:

```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                       (size)   Mode  Cnt      Score   Error  Units
[info] ExtractFieldsReading.scalaJack       1  thrpt       26638.053          ops/s
[info] ExtractFieldsReading.scalaJack      10  thrpt        3909.127          ops/s
[info] ExtractFieldsReading.scalaJack     100  thrpt         397.262          ops/s
[info] ExtractFieldsReading.scalaJack    1000  thrpt          15.173          ops/s
[info] ExtractFieldsReading.scalaJack   10000  thrpt           0.199          ops/s
[info] ExtractFieldsReading.scalaJack  100000  thrpt           0.002          ops/s
```

To run that benchmarks on your JDK:
1. [Install latest version of `sbt`](https://www.scala-sbt.org/1.0/docs/Setup.html) and/or ensure that it already installed properly: 
```
sbt about
```

2. Clone `jsoniter-scala` repo: 
```
git clone https://github.com/plokhotnyuk/jsoniter-scala.git
```

3. Enter to the cloned directory and checkout for the specific branch:
```
cd jsoniter-scala
git checkout ScalaJack-DoS-by-hashmap-collisions
```

4. Run benchmarks using a path parameter to your JDK:
```
sbt -no-colors 'jsoniter-scala-benchmark/jmh:run -jvm /usr/lib/jvm/jdk-11/bin/java -wi 1 -i 1 -p size=1,10,100,1000,10000,100000 ExtractFields.*scalaJack'
```

**Comment by gzoller** [comment]
Interesting.... I'll give it a try.   It's quite possible something in the 6 series cracked efficiency. 
 Your benchmark will be a great help.  Keeping ticket open.

**Comment by gzoller** [comment]
Hello, plokhotnyuk...  Again thank you for the benchmark, but I'm having trouble running it.  I really want to see what you're seeing.  Following the instructions given I get this error:

`[warn] bootstrap class path not set in conjunction with -source 8
[info] Done compiling.
[info] Done compiling.
[info] running (fork) org.openjdk.jmh.Main -jvm /usr/lib/jvm/jdk-11/bin/java -wi 1 -i 1 -p size=1,10,100,1000,10000,100000 ExtractFields.*scalaJack
[error] WARNING: An illegal reflective access operation has occurred
[error] WARNING: Illegal reflective access by org.openjdk.jmh.util.Utils (file:/private/var/folders/ph/ccz4n1qs62n0bn8mqdg94gsw0000gp/T/sbt_ebf3c641/target/e752ff01/c82dacdf/jmh-core-1.21.jar) to field java.io.PrintStream.charOut
[error] WARNING: Please consider reporting this to the maintainers of org.openjdk.jmh.util.Utils
[error] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[error] WARNING: All illegal access operations will be denied in a future release
[error] Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/lib/jvm/jdk-11/bin/java": error=2, No such file or directory
[error] 	at org.openjdk.jmh.util.Utils.readPropertiesFromCommand(Utils.java:538)
[error] 	at org.openjdk.jmh.runner.Runner.newBenchmarkParams(Runner.java:479)
[error] 	at org.openjdk.jmh.runner.Runner.getActionPlans(Runner.java:363)
[error] 	at org.openjdk.jmh.runner.Runner.runBenchmarks(Runner.java:549)
[error] 	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:320)
[error] 	at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
[error] 	at org.openjdk.jmh.Main.main(Main.java:71)
[error] Caused by: java.io.IOException: Cannot run program "/usr/lib/jvm/jdk-11/bin/java": error=2, No such file or directory
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error] 	at org.openjdk.jmh.util.Utils.readPropertiesFromCommand(Utils.java:521)
[error] 	... 6 more
[error] Caused by: java.io.IOException: error=2, No such file or directory
[error] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[error] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[error] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[error] 	... 8 more
[error] Nonzero exit code returned from runner: 1
[error] (jsoniter-scala-benchmark / Jmh / run) Nonzero exit code returned from runner: 1
[error] Total time: 302 s (05:02), completed Oct 2, 2019, 10:03:39 PM`

**Comment by plokhotnyuk** [comment]
Hi, Greg!

You can skip the `-jvm <absolute_path_to_jvm>` parameter. Here is a minimum command to reproduce the problem:
```
sbt 'jsoniter-scala-benchmark/jmh:run -wi 1 -i 1 -p size=1,10,100,1000,10000,100000 ExtractFields.*scalaJack'
```

**Comment by plokhotnyuk** [comment]
Also, you can use some profilers. Below is a screenshot of an interactive flame graph SVG file which shows CPU usage through the call stack. It was get by the following command which require paths to the cloned repos of [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) and [FlameGraph](https://github.com/brendangregg/FlameGraph) tools:
```
sbt 'jsoniter-scala-benchmark/jmh:run -prof "jmh.extras.Async:event=cpu;dir=/tmp/profile-async;asyncProfilerDir=/home/andriy/Projects/com/github/jvm-profiling-tools/async-profiler;flameGraphDir=/home/andriy/Projects/com/github/brendangregg/FlameGraph;flameGraphOpts=--color,java;verbose=true" -wi 5 -i 25 -p size=10000 ExtractFields.*scalaJack'
```
![image](https://user-images.githubusercontent.com/890289/66123925-67018300-e5e3-11e9-9724-ec0134e219cc.png)

**Comment by gzoller** [comment]
Here's my progress so far: I was able to re-run your ScalaJack benchmark.  Results weren't good.  Next I tried to run with the profiler as shown above.  Here was the error I got:

```
784f43a24fb5:jsoniter-scala wmy965$ sbt 'jsoniter-scala-benchmark/jmh:run -prof "jmh.extras.Async:event=cpu;dir=/tmp/profile-async;asyncProfilerDir=/Users/wmy965/git/async-profiler;flameGraphDir=/Users/wmy965/git/FlameGraph;flameGraphOpts=--color,java;verbose=true" -wi 5 -i 25 -p size=10000 ExtractFields.*scalaJack'
[info] Loading settings for project global-plugins from idea.sbt,scalariform.sbt ...
[info] Loading global plugins from /Users/wmy965/.sbt/1.0/plugins
[info] Loading settings for project jsoniter-scala-build from plugins.sbt ...
[info] Loading project definition from /Users/wmy965/git/jsoniter-scala/project
[info] Loading settings for project jsoniter-scala from release.sbt,version.sbt,build.sbt ...
[info] Set current project to jsoniter-scala (in build file:/Users/wmy965/git/jsoniter-scala/)
Processing 2933 classes from /Users/wmy965/git/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/classes with "reflection" generator
Writing out Java source to /Users/wmy965/git/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/src_managed/jmh and resources to /Users/wmy965/git/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/resource_managed/jmh
[info] running (fork) org.openjdk.jmh.Main -prof jmh.extras.Async:event=cpu;dir=/tmp/profile-async;asyncProfilerDir=/Users/wmy965/git/async-profiler;flameGraphDir=/Users/wmy965/git/FlameGraph;flameGraphOpts=--color,java;verbose=true -wi 5 -i 25 -p size=10000 ExtractFields.*scalaJack
[error] WARNING: An illegal reflective access operation has occurred
[error] WARNING: Illegal reflective access by org.openjdk.jmh.util.Utils (file:/private/var/folders/ph/ccz4n1qs62n0bn8mqdg94gsw0000gp/T/sbt_fed5da3b/target/e752ff01/c82dacdf/jmh-core-1.21.jar) to field java.io.PrintStream.charOut
[error] WARNING: Please consider reporting this to the maintainers of org.openjdk.jmh.util.Utils
[error] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[error] WARNING: All illegal access operations will be denied in a future release
[info] /Users/wmy965/git/async-profiler/build/libasyncProfiler.so does not exist
[error] Profilers failed to initialize, exiting.
[error] Nonzero exit code returned from runner: 1
[error] (jsoniter-scala-benchmark / Jmh / run) Nonzero exit code returned from runner: 1
[error] Total time: 14 s, completed Oct 4, 2019, 9:02:09 AM
```

Curious, I dusted off my original ScalaJack benchmark code and ran it against SJ5 and Circe.  Something did happen between SJ5 and SJ6.  SJ5 was about the same as Circe.  SJ6 was only about 1/2 as fast for that test--a significant drop!  I isolated just the JSON tokenization on all 3 and they were all about the same, so it's the post-tokenizing parsing that's causing trouble.  More to learn...

**Comment by plokhotnyuk** [comment]
@gzoller I've missed a step that async-profiler should be built according to the instructions in its README doc.

**Comment by gzoller** [comment]
Sorry for all the issues.  I did successfully build async-profiler and re-ran the above command.  The output is below.  I'm not seeing any artifacts generated (assuming due to the NaN).  It looks like the test ran and it didn't complain about not finding the Async profiler, but somehow it doesn't look like it is communicating.

```
[info] Loading settings for project global-plugins from idea.sbt,scalariform.sbt ...
[info] Loading global plugins from /Users/wmy965/.sbt/1.0/plugins
[info] Loading settings for project jsoniter-scala-build from plugins.sbt ...
[info] Loading project definition from /Users/wmy965/git/jsoniter-scala/project
[info] Loading settings for project jsoniter-scala from release.sbt,version.sbt,build.sbt ...
[info] Set current project to jsoniter-scala (in build file:/Users/wmy965/git/jsoniter-scala/)
Processing 2933 classes from /Users/wmy965/git/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/classes with "reflection" generator
Writing out Java source to /Users/wmy965/git/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/src_managed/jmh and resources to /Users/wmy965/git/jsoniter-scala/jsoniter-scala-benchmark/target/scala-2.13/resource_managed/jmh
[info] running (fork) org.openjdk.jmh.Main -prof jmh.extras.Async:event=cpu;dir=/tmp/profile-async;asyncProfilerDir=/Users/wmy965/git/async-profiler;flameGraphDir=/Users/wmy965/git/FlameGraph;flameGraphOpts=--color,java;verbose=true -wi 5 -i 25 -p size=10000 ExtractFields.*scalaJack
[info] # JMH version: 1.21
[info] # VM version: JDK 1.8.0_191, Java HotSpot(TM) 64-Bit Server VM, 25.191-b12
[info] # VM invoker: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/bin/java
[info] # VM options: -server -Xms2g -Xmx2g -XX:NewSize=1g -XX:MaxNewSize=1g -XX:InitialCodeCacheSize=512m -XX:ReservedCodeCacheSize=512m -XX:+UseParallelGC -XX:MaxInlineLevel=18 -XX:-UseBiasedLocking -XX:+AlwaysPreTouch
[info] # Warmup: 5 iterations, 1 s each
[info] # Measurement: 25 iterations, 1 s eachgeBin 2s
[info] # Timeout: 10 min per iteration
[info] # Threads: 1 thread, will synchronize iterations
[info] # Benchmark mode: Throughput, ops/time
[info] # Benchmark: com.github.plokhotnyuk.jsoniter_scala.benchmark.ExtractFieldsReading.scalaJack
[info] # Parameters: (size = 10000)
[info] # Run progress: 0.00% complete, ETA 00:00:30
[info] # Fork: 1 of 1
[info] # Preparing profilers: Async
[info] # Warmup Iteration   1: 0.111 ops/s
[info] # Warmup Iteration   2: 0.164 ops/s
[info] # Warmup Iteration   3: 0.186 ops/s
[info] # Warmup Iteration   4: 0.195 ops/s
[info] # Warmup Iteration   5: 0.202 ops/s
[info] Iteration   1: /Users/wmy965/git/async-profiler/build/jattach 5372 load /Users/wmy965/git/async-profiler/build/libasyncProfiler.so true start,event=cpu,framebuf=8388608,interval=1000000
[info] Connected to remote JVM
[info] Response code = Started [cpu] profiling
[info] 0
[info] 0
[info] 0.184 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration   2: 0.191 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration   3: 0.153 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration   4: 0.176 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration   5: 0.178 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration   6: 0.175 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration   7: 0.185 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration   8: 0.182 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration   9: 0.186 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  10: 0.181 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  11: 0.191 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  12: 0.158 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  13: 0.185 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  14: 0.159 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  15: 0.104 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  16: 0.121 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  17: 0.131 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  18: 0.104 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  19: 0.099 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  20: 0.141 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  21: 0.150 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  22: 0.151 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  23: 0.144 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  24: 0.159 ops/s
[info]                  async-profiler: NaN N/A
[info] Iteration  25: /Users/wmy965/git/async-profiler/build/jattach 5372 load /Users/wmy965/git/async-profiler/build/libasyncProfiler.so true stop,file=/tmp/profile-async/collapsed-cpu.txt,collapsed
[info] Connected to remote JVM
[info] Response code = 0
[info] 0
[info] /Users/wmy965/git/async-profiler/build/jattach 5372 load /Users/wmy965/git/async-profiler/build/libasyncProfiler.so true file=/tmp/profile-async/cpu.jfr,jfr
[info] Connected to remote JVM
[info] Response code = 0
[info] 0
[info] /Users/wmy965/git/async-profiler/build/jattach 5372 load /Users/wmy965/git/async-profiler/build/libasyncProfiler.so true stop,file=/tmp/profile-async/summary.txt,summary
[info] Connected to remote JVM
[info] Response code = 0
[info] 0
[info] perl /Users/wmy965/git/FlameGraph/flamegraph.pl --color java /tmp/profile-async/collapsed-cpu.txt
[info] perl /Users/wmy965/git/FlameGraph/flamegraph.pl --color java --reverse /tmp/profile-async/collapsed-cpu.txt
[info] 0.149 ops/s
[info]                  async-profiler: NaN N/A
[info] # Processing profiler results: Async
[info] Result "com.github.plokhotnyuk.jsoniter_scala.benchmark.ExtractFieldsReading.scalaJack":
[info]   0.157 ±(99.9%) 0.021 ops/s [Average]
[info]   (min, avg, max) = (0.099, 0.157, 0.191), stdev = 0.028
[info]   CI (99.9%): [0.136, 0.179] (assumes normal distribution)
[info] Secondary result "com.github.plokhotnyuk.jsoniter_scala.benchmark.ExtractFieldsReading.scalaJack:async-profiler":
[info] /tmp/profile-async/collapsed-cpu.txt
[info] /tmp/profile-async/cpu.jfr
[info] /tmp/profile-async/summary.txt
[info] /tmp/profile-async/flame-graph-cpu.svg
[info] /tmp/profile-async/flame-graph-cpu-reverse.svg
[info] # Run complete. Total time: 00:03:23
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                                      (size)   Mode  Cnt  Score   Error  Units
[info] ExtractFieldsReading.scalaJack                  10000  thrpt   25  0.157 ± 0.021  ops/s
[info] ExtractFieldsReading.scalaJack:async-profiler   10000  thrpt         NaN            N/A
[success] Total time: 222 s (03:42), completed Oct 4, 2019 4:51:25 PM
```

**Comment by plokhotnyuk** [comment]
Well done! Please open *.svg files from your /tmp/profile-acync directory.

More info about profilers and flame graphs see in JMH docs and blog articles like here:
http://www.brendangregg.com/flamegraphs.html
https://www.lightbend.com/blog/profiling-jvm-applications
https://www.hacksnews.com/profiling-java-purposes-with-async-profiler/

**Comment by gzoller** [comment]
I think I've cracked the nut... or said more accurately, I have an explanation.  ScalaJack's current entry point is this:

`def read[T](wire: WIRE)(implicit tt: TypeTag[T]): T` 

From there, ScalaJack looks at tt.tpe to figure out the Type and then on to all the specifics of parsing and marshaling the object.  The tt.tpe is the speed-killer.  (I ran a test that hard-wired around that one thing and it gave me numbers competitive to Circe.)  There's a very high cost to tt.tpe, apparently.  Perhaps some lazy computation, who knows... mysteries of Scala.  Where Circe gets its speed is due to macros it can figure out the Type, and the appropriate TypeAdapter (in ScalaJack's nomenclature) at compile-time. 

So clearly that kind of open-ended inferring ability is a key capability of ScalaJack, and it's huge cost burden.  Is there anything that can be done?  I don't want to give up the features of ScalaJack that make it stand out, otherwise why not just use another mature parser.  

I think that parsing is frequently repetitive--people parse the same thing in loops.  For this common use case, it should be passible to add a function to ScalaJack to retrieve the TypeAdapter for a type, cache it and re-use it.  (Basically you pay the cost of tt.tpe only once.)  That should give us some air!

Keeping ticket open until I can implement this feature and run a few tests.

**Comment by plokhotnyuk** [comment]
Beside performance, TypeTag has quite severe issues when used with JIT compiler and it seems impossible to make it work with AOT compiler: https://t.co/AGO5t1p15u

**Comment by gzoller** [comment]
Ok, so this took a lot longer than I'd hoped--it was a big job, but I've done a major refactor of the internals to recapture speed lost between SJ5 and 6.  In particular In ScalaJack 6.1.0 there is now sj.forType[SomeType] for a faster "type-locked" ScalaJack to use in the common case when you're repetitively parsing the same type again and again (it avoids repeated reflection calls).

I'd value your thoughts!

**Comment by plokhotnyuk** [comment]
@gzoller Nice! I think that the security issue can be closed, but still there is a room for improvements, especially for small messages with 10 or less fields.

I've run the benchmark for the `6.1.0` version using the following command:
```
sbt -java-home /usr/lib/jvm/openjdk-11 -no-colors 'jsoniter-scala-benchmark/jmh:run -wi 3 -i 3 -p size=1,10,100,1000,10000,100000 ExtractFields.*'
```

Below are results for 10 JSON parsers for Scala, including ScalaJack:
```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                              (size)   Mode  Cnt        Score         Error  Units
[info] ExtractFieldsReading.avSystemGenCodec       1  thrpt    3  2579339.193 ±   70340.979  ops/s
[info] ExtractFieldsReading.avSystemGenCodec      10  thrpt    3   432560.366 ±    4888.222  ops/s
[info] ExtractFieldsReading.avSystemGenCodec     100  thrpt    3    48087.504 ±    4855.606  ops/s
[info] ExtractFieldsReading.avSystemGenCodec    1000  thrpt    3     4320.139 ±    2250.165  ops/s
[info] ExtractFieldsReading.avSystemGenCodec   10000  thrpt    3      429.281 ±     306.238  ops/s
[info] ExtractFieldsReading.avSystemGenCodec  100000  thrpt    3       42.266 ±      22.593  ops/s
[info] ExtractFieldsReading.borerJson              1  thrpt    3  2581215.911 ±   25921.113  ops/s
[info] ExtractFieldsReading.borerJson             10  thrpt    3   554091.494 ±  145507.286  ops/s
[info] ExtractFieldsReading.borerJson            100  thrpt    3    59344.299 ±     223.581  ops/s
[info] ExtractFieldsReading.borerJson           1000  thrpt    3     6109.850 ±      72.595  ops/s
[info] ExtractFieldsReading.borerJson          10000  thrpt    3      602.455 ±       8.663  ops/s
[info] ExtractFieldsReading.borerJson         100000  thrpt    3       64.317 ±       1.425  ops/s
[info] ExtractFieldsReading.circe                  1  thrpt    3  1456565.471 ±   68092.434  ops/s
[info] ExtractFieldsReading.circe                 10  thrpt    3   249420.008 ±  126487.482  ops/s
[info] ExtractFieldsReading.circe                100  thrpt    3    21493.816 ±   18343.335  ops/s
[info] ExtractFieldsReading.circe               1000  thrpt    3     1853.543 ±    1131.302  ops/s
[info] ExtractFieldsReading.circe              10000  thrpt    3      153.815 ±      56.796  ops/s
[info] ExtractFieldsReading.circe             100000  thrpt    3       13.082 ±       5.465  ops/s
[info] ExtractFieldsReading.dslJsonScala           1  thrpt    3  5634142.578 ±  297717.847  ops/s
[info] ExtractFieldsReading.dslJsonScala          10  thrpt    3   897909.491 ±    5896.868  ops/s
[info] ExtractFieldsReading.dslJsonScala         100  thrpt    3   110379.128 ±     850.744  ops/s
[info] ExtractFieldsReading.dslJsonScala        1000  thrpt    3    12524.639 ±     392.149  ops/s
[info] ExtractFieldsReading.dslJsonScala       10000  thrpt    3     1188.781 ±      32.581  ops/s
[info] ExtractFieldsReading.dslJsonScala      100000  thrpt    3      120.082 ±       1.202  ops/s
[info] ExtractFieldsReading.jacksonScala           1  thrpt    3  1476185.658 ±   30715.989  ops/s
[info] ExtractFieldsReading.jacksonScala          10  thrpt    3   283343.869 ±    1337.695  ops/s
[info] ExtractFieldsReading.jacksonScala         100  thrpt    3    31727.772 ±     451.473  ops/s
[info] ExtractFieldsReading.jacksonScala        1000  thrpt    3     3174.444 ±      18.125  ops/s
[info] ExtractFieldsReading.jacksonScala       10000  thrpt    3      242.350 ±      10.749  ops/s
[info] ExtractFieldsReading.jacksonScala      100000  thrpt    3       25.151 ±       3.318  ops/s
[info] ExtractFieldsReading.jsoniterScala          1  thrpt    3  8297096.850 ± 2488925.345  ops/s
[info] ExtractFieldsReading.jsoniterScala         10  thrpt    3  1626071.571 ±  494945.437  ops/s
[info] ExtractFieldsReading.jsoniterScala        100  thrpt    3   161666.310 ±    2225.923  ops/s
[info] ExtractFieldsReading.jsoniterScala       1000  thrpt    3    16678.351 ±     783.341  ops/s
[info] ExtractFieldsReading.jsoniterScala      10000  thrpt    3     1668.877 ±       4.129  ops/s
[info] ExtractFieldsReading.jsoniterScala     100000  thrpt    3      167.497 ±       2.068  ops/s
[info] ExtractFieldsReading.playJson               1  thrpt    3  1008065.013 ±    2427.257  ops/s
[info] ExtractFieldsReading.playJson              10  thrpt    3   174040.344 ±    1617.914  ops/s
[info] ExtractFieldsReading.playJson             100  thrpt    3    16367.160 ±      94.262  ops/s
[info] ExtractFieldsReading.playJson            1000  thrpt    3     1436.118 ±      93.919  ops/s
[info] ExtractFieldsReading.playJson           10000  thrpt    3       44.289 ±       3.019  ops/s
[info] ExtractFieldsReading.playJson          100000  thrpt    3        4.959 ±       1.464  ops/s
[info] ExtractFieldsReading.scalaJack              1  thrpt    3   383071.660 ±    5891.133  ops/s
[info] ExtractFieldsReading.scalaJack             10  thrpt    3   278393.026 ±   18694.096  ops/s
[info] ExtractFieldsReading.scalaJack            100  thrpt    3    72936.241 ±    8025.399  ops/s
[info] ExtractFieldsReading.scalaJack           1000  thrpt    3     8769.686 ±     458.505  ops/s
[info] ExtractFieldsReading.scalaJack          10000  thrpt    3      659.502 ±     837.026  ops/s
[info] ExtractFieldsReading.scalaJack         100000  thrpt    3       59.893 ±       4.035  ops/s
[info] ExtractFieldsReading.sprayJson              1  thrpt    3  1256454.851 ±    9640.213  ops/s
[info] ExtractFieldsReading.sprayJson             10  thrpt    3   172461.480 ±  140297.364  ops/s
[info] ExtractFieldsReading.sprayJson            100  thrpt    3    15781.123 ±   13831.632  ops/s
[info] ExtractFieldsReading.sprayJson           1000  thrpt    3     1496.647 ±     681.331  ops/s
[info] ExtractFieldsReading.sprayJson          10000  thrpt    3      135.785 ±      73.527  ops/s
[info] ExtractFieldsReading.sprayJson         100000  thrpt    3       12.065 ±       4.124  ops/s
[info] ExtractFieldsReading.uPickle                1  thrpt    3  1126782.219 ±  506519.158  ops/s
[info] ExtractFieldsReading.uPickle               10  thrpt    3   170749.411 ±  126631.493  ops/s
[info] ExtractFieldsReading.uPickle              100  thrpt    3    18927.106 ±   13727.609  ops/s
[info] ExtractFieldsReading.uPickle             1000  thrpt    3     1929.694 ±    1359.000  ops/s
[info] ExtractFieldsReading.uPickle            10000  thrpt    3      198.284 ±     112.726  ops/s
[info] ExtractFieldsReading.uPickle           100000  thrpt    3       19.585 ±      15.777  ops/s
```

**Comment by gzoller** [comment]
Thanks!  I love this picture!  It's more nuanced than my single benchmark on my site.  Different parsers are faster/"better" for different scenarios and ScalaJack sits nicely and competitively in that domain--some faster, some slower, depending on usage.
