### ISSUE TITLE
Reading a Mongo doc gives NoSuchElementException: None.get

### ISSUE THREAD

**Issue by jayv** [gzoller/ScalaJack#53]
Using v4.7.0

Model
```scala
case class NetworkRules(_id: String, network:String, rules:List[StreamRule])
case class StreamRule(urn:String, terms: List[TermRule] = List.empty, authors: List[AuthorRule] = List.empty)
case class AuthorRule(id:String, name: String)
case class TermRule(terms: List[String])
```

Data
```json
Document((_id,BsonString{value='main'}), (network,BsonString{value='main'}), (rules,BsonArray{values=[{ "urn" : "12dogfashion", "terms" : [{ "terms" : ["dog", "fashion"] }], "authors" : [] }, { "urn" : "123dog", "terms" : [{ "terms" : ["dog"] }], "authors" : [] }, { "urn" : "987good", "terms" : [{ "terms" : ["good"] }], "authors" : [] }, { "urn" : "988good_dog", "terms" : [{ "terms" : ["good", "dog"] }], "authors" : [] }, { "urn" : "775boys", "terms" : [{ "terms" : ["boys"] }], "authors" : [] }, { "urn" : "55fashion", "terms" : [{ "terms" : ["fashion"] }], "authors" : [] }, { "urn" : "33iphone", "terms" : [{ "terms" : ["iphone"] }], "authors" : [] }, { "urn" : "36iphonefashion", "terms" : [{ "terms" : ["fashion", "iphone"] }], "authors" : [] }]}))
```

Trace
```scala
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at co.blocke.scalajack.CCType$$anonfun$1.apply(Model.scala:32)
	at co.blocke.scalajack.CCType$$anonfun$1.apply(Model.scala:32)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.LinkedHashMap.foreach(LinkedHashMap.scala:139)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at co.blocke.scalajack.CCType.materialize(Model.scala:32)
	at co.blocke.scalajack.mongo.MongoJackFlavor$MongoReadRenderer._makeClass(MongoFlavor.scala:76)
	at co.blocke.scalajack.mongo.MongoJackFlavor$MongoReadRenderer.co$blocke$scalajack$mongo$MongoJackFlavor$MongoReadRenderer$$parse(MongoFlavor.scala:82)
	at co.blocke.scalajack.mongo.MongoJackFlavor$MongoReadRenderer.read(MongoFlavor.scala:33)
	at co.blocke.scalajack.mongo.MongoJackFlavor$MongoReadRenderer.read(MongoFlavor.scala:31)
	at co.blocke.scalajack.ScalaJack$class.read(ScalaJack.scala:26)
	at co.blocke.scalajack.mongo.MongoFlavor$MongoScalaJack.read(MongoFlavor.scala:26)

```

**Comment by gzoller** [comment]
I was able to replicate this problem.  Let me see what's going on with it.  Thanks for submitting it!

**Comment by gzoller** [comment]
OK, I think I see the problem.  In NetworkRules you have a field called _id.  This is a Mongo name pattern, so you shouldn't name your case class field _id.  You annotate a field with @DBKey and ScalaJack will convert it back 'n forth to _id in the background.  So this class should be:
```scala
case class NetworkRules(
	@DBKey some_name_here: String, 
	network:String, 
	rules:List[StreamRule])
```
If you do it like that it should work.

**Comment by jayv** [comment]
cool will try when i get back next week

On Thursday, June 2, 2016, Greg Zoller <notifications@github.com> wrote:

> OK, I think I see the problem. In NetworkRules you have a field called
> _id. This is a Mongo name pattern, so you shouldn't name your case class
> field _id. You annotate a field with @DBKey <https://github.com/DBKey>
> and ScalaJack will convert it back 'n forth to _id in the background. So
> this class should be:
>
> case class NetworkRules(
>     @DBKey some_name_here: String,
>     network:String,
>     rules:List[StreamRule])
>
> If you do it like that it should work.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gzoller/ScalaJack/issues/53#issuecomment-223432843>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAJuXWKLLMqPcp-4nJIzrpESU2qmnVVKks5qH09mgaJpZM4IrQqq>
> .
>


-- 
- Jo Voordeckers

**Comment by jayv** [comment]
It works, already prefer it to reactivemongo.
